services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: "python bot.py"
